### ISSUE TITLE
Decorate resources for serialization

### ISSUE THREAD

**Issue by krzysiek1507** [vasilakisfil/SimpleAMS#26]
Hi. I'd like to serialize relations inside my records decorated using my decorators instead of declaring methods in a serializer. E.g. `UserDecorator#full_name`. Is there any way to declare a decorator for a serializer?

The code below rises: 
```ruby
NoMethodError (undefined method `full_name' for #<User:0x00007fe37d4f0700>)
```

```ruby
# frozen_string_literal: true

class User
  attr_reader :first_name, :last_name

  def initialize(first_name:, last_name:)
    @first_name = first_name
    @last_name = last_name
  end
end

class Event
  # in real life it would be e.g. ActiveRecord relation
  def users
    [User.new(first_name: 'John', last_name: 'Smith'), User.new(first_name: 'Donald', last_name: 'Schmidt')]
  end
end

class UserDecorator < SimpleDelegator
  def full_name
    "#{first_name} #{last_name}"
  end
end

class UserSerializer
  include SimpleAMS::DSL

  adapter SimpleAMS::Adapters::AMS

  attributes :full_name
end

class EventSerializer
  include SimpleAMS::DSL

  adapter SimpleAMS::Adapters::AMS

  has_many :users, serializer: UserSerializer
end
```

Maybe something like would be a solution?
```ruby
class UserSerializer
  include SimpleAMS::DSL

  adapter SimpleAMS::Adapters::AMS

  attributes :full_name

  decorate_with UserDecorator
end
```

`decorate_with` would be called on the resource.

**Comment by vasilakisfil** [comment]
I think the best is to decorate them before you pass them into the serializer. For instance:

```
class Event
  # in real life it would be e.g. ActiveRecord relation
  def users
    [User.new(first_name: 'John', last_name: 'Smith'), User.new(first_name: 'Donald', last_name: 'Schmidt')].map(&:decorate)
  end
end
```

**Comment by krzysiek1507** [comment]
It's not possible when `users` is a relation, e.g.

```ruby
class User < ActiveRecord::Base
  belongs_to :event
end

class Event < ActiveRecord::Base
  has_many :users
end
```

So I cannot decorate `Event#users` because that's an object I can query like e.g. `order(:name).select(:id)`.

**Comment by vasilakisfil** [comment]
Maybe I am missing something, but can't you decorate after you query it? Yes, you need to create a method that overrides the `users`, but that's where you can decorate it:

```
def users
  object.users.where(admin: false).order(:name).select(:id, :first_name, :last_name).map(&:decorate)
end
```

the key here is that you decorate it just before the serializer uses it (hence the `map`).

**Comment by krzysiek1507** [comment]
Nope, I can't do this in model because it would affect the whole app. I could use ValueObjects but it doesn't seem reasonable when I need to serialize just records from the db.

**Comment by vasilakisfil** [comment]
no I mean, in the serializer. Like, let's say that you have an `Event` and a `User` model and the following serializers:

```
class UserSerializer
  include SimpleAMS::DSL

  adapter SimpleAMS::Adapters::AMS

  attributes :full_name
end

class EventSerializer
  include SimpleAMS::DSL

  adapter SimpleAMS::Adapters::AMS

  has_many :users, serializer: UserSerializer

  def users
    object.users.query(...).map(&:decorate)
  end
end
```

You just need to override the users method in Event model (or decorator) and decorate the list of users.

**Comment by krzysiek1507** [comment]
That's a solution but for collection serialization it requires:
```ruby
SimpleAMS::Renderer::Collection.new(events.map(&:decorate), serializer: EventSerializer).as_json
```
and to override the methods in every serializer.

**Comment by vasilakisfil** [comment]
Regarding overriding the methods on every serializer, you could add the `users` method inside the decorator that decorates the users from there, and keeping your serializers clean.

**Comment by vasilakisfil** [comment]
Closing here, feel free to re-open if you have questions.
