### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by pmackay** [vasilakisfil/SimpleAMS#29]
It can be really useful to have a CHANGELOG file in a project that is independent of GitHub releases.

**Comment by vasilakisfil** [comment]
Can you elaborate ? Do you argue that the changelog should contain what a github release contains? And the purpose of that is to be platform (like github) independent ?

**Comment by pmackay** [comment]
I think I've seen more projects that have a CHANGELOG file than use GitHub releases for documenting changes. The docs at https://keepachangelog.com/en/1.0.0/ describe the benefits and motivations very well and have a section on Github Releases. A log that is part of the git repo (wherever it might be) is a useful thing.

**Comment by vasilakisfil** [comment]
Closing since it was fixed by #45. Thanks!
