### ISSUE TITLE
Serializing a polymorphic list

### ISSUE THREAD

**Issue by pmackay** [vasilakisfil/SimpleAMS#30]
As an example, if I had a Board model that had a list of Shapes, which could be any of Circle, Rectangle, etc, how could I define a Board serializer that has a `has_many :shapes` association where shapes could a mix of models?

**Comment by vasilakisfil** [comment]
you can pass a lambda in the serializer, inside the parent serializer (I suspect BoardSerializer).

```
has_many :shapes, serializer: ->(obj, s){
  case obj
  when Circle
    CircleSerializer
  when Rectangle
    RectangleSerializer
  else
    ShapeSerializer
}
```

**Comment by pmackay** [comment]
OK great, that's helpful, thanks :) Could be useful to add that to the README or the wiki for reference? Happy to add a Tips section PR if useful.

**Comment by vasilakisfil** [comment]
Yes I intend to restructure the Readme actually this weekend with more extensive examples and use cases.

**Comment by vasilakisfil** [comment]
Closing here, feel free to re-open a new one if you have questions.
