### ISSUE TITLE
Enforce definite code style

### ISSUE THREAD

**Issue by funk-yourself** [vasilakisfil/SimpleAMS#35]
There's such mention in README:

>  I will be very picky on the code style and design, to match (my) existing code characteristics

But there's no CI workflow to check code style, even rubocop config is not present. I suggest to introduce rubocop into the project and formalize code style rules with it.

**Comment by pmackay** [comment]
Would be interesting to know if https://github.com/testdouble/standard would satisfy the requirements, and if not what the delta is :)

**Comment by vasilakisfil** [comment]
What I meant is not the style in terms of how many spaces you leave, how to wrap big lines etc, for that I would love to use something standard like what @pmackay suggested (I actually already looking into it). I meant more, how you design the code, even a single method, how you name it, what you inject etc.

But as I said I am happy to add  https://github.com/testdouble/standard so we stop fighting about the basics :)

**Comment by vasilakisfil** [comment]
I think this now can be closed by #37 and #39.
