### ISSUE TITLE
Custom key name

### ISSUE THREAD

**Issue by danilolic** [vasilakisfil/SimpleAMS#38]
Hi, I'm migrating some AMS code to SimpleAMS. Using AMS I have an alias feature where I can change the key name like that:

```ruby
attribute :foo, key: :bar
```
So JSON renders bar instead of foo

SimpleAMS has some similar feature?

**Comment by vasilakisfil** [comment]
not in a DSL, but you can have `attribute :bar` and then define a method:

```
def foo
  object.bar
end
```

**Comment by vasilakisfil** [comment]
closing here, feel free to reopen if the answer didn't cover your question.
